baseURL = 'https://fulgerr.github.io/my-hugo-website'
languageCode = 'en-us'
theme = "hextra"
title = 'UiPath Documentation'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # ... other params ...

  [params.theme]
    gitRepo = "https://github.com/Fulgerr/my-hugo-website/"
    gitBranch = "main"
    [params.theme.editURL]
      enable = true